# Generated by Django 6.0.4 on 2026-05-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='ID oficial de la liga en API-Football', unique=True)),
                ('name', models.CharField(help_text='Nombre de la liga', max_length=100)),
                ('country', models.CharField(help_text='País de la liga', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo de la liga', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='ID oficial del equipo en API-Football', unique=True)),
                ('name', models.CharField(help_text='Nombre del equipo', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='URL del escudo del equipo', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='ID oficial del partido en API-Football', unique=True)),
                ('starts_at', models.DateTimeField(help_text='Fecha y hora de inicio del evento')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_play', 'En Vivo'), ('finished', 'Finalizado'), ('suspended', 'Suspendido'), ('cancelled', 'Anulado')], default='scheduled', help_text='Estado actual del evento', max_length=20)),
                ('home_score', models.IntegerField(blank=True, help_text='Goles anotados por el equipo local', null=True)),
                ('away_score', models.IntegerField(blank=True, help_text='Goles anotados por el equipo visitante', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Última actualización local del evento')),
                ('league', models.ForeignKey(help_text='Liga a la que pertenece el evento', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='betting.league')),
                ('away_team', models.ForeignKey(help_text='Equipo visitante', on_delete=django.db.models.deletion.PROTECT, related_name='away_events', to='betting.team')),
                ('home_team', models.ForeignKey(help_text='Equipo local', on_delete=django.db.models.deletion.PROTECT, related_name='home_events', to='betting.team')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del mercado de apuestas (ej. 1X2, Over/Under 2.5, BTTS)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el mercado está abierto para recibir apuestas')),
                ('event', models.ForeignKey(help_text='Evento al que pertenece el mercado', on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='betting.event')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la opción (ej. Gana Local, Empate, Gana Visitante, Over, Under, Yes, No)', max_length=100)),
                ('odds', models.DecimalField(decimal_places=4, help_text='Valor decimal de la cuota con el margen de la casa aplicado', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta selección específica está habilitada para apostar')),
                ('market', models.ForeignKey(help_text='Mercado al que pertenece la selección', on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.market')),
            ],
        ),
    ]
