# Generated by Django 6.0.4 on 2026-05-27 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Aceptada'), ('won', 'Ganada'), ('lost', 'Perdida'), ('cancelled', 'Cancelada / Anulada'), ('cashed_out', 'Cobro Anticipado')], default='accepted', help_text='Estado actual del boleto de apuesta', max_length=20)),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('accumulator', 'Combinada')], default='simple', help_text='Tipo de apuesta (simple o combinada)', max_length=20)),
                ('stake', models.DecimalField(decimal_places=4, help_text='Monto de fichas apostado', max_digits=18)),
                ('potential_payout', models.DecimalField(decimal_places=4, help_text='Retorno potencial calculado', max_digits=18)),
                ('idempotency_key', models.UUIDField(db_index=True, help_text='Clave UUID única para evitar cobros o registros dobles', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de colocación de la apuesta')),
                ('settled_at', models.DateTimeField(blank=True, help_text='Fecha y hora en la que se liquidó la apuesta', null=True)),
                ('user', models.ForeignKey(help_text='Usuario que realizó la apuesta', on_delete=django.db.models.deletion.PROTECT, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_at_bet', models.DecimalField(decimal_places=4, help_text='Cuota decimal capturada al momento exacto de apostar', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('won', 'Ganada'), ('lost', 'Perdida'), ('void', 'Anulada')], default='pending', help_text='Estado de resolución de esta selección individual', max_length=20)),
                ('bet', models.ForeignKey(help_text='Boleto de apuesta al que pertenece esta selección', on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.bet')),
                ('selection', models.ForeignKey(help_text='Selección deportiva elegida', on_delete=django.db.models.deletion.PROTECT, to='betting.selection')),
            ],
        ),
    ]
