# Generated by Django 6.0.4 on 2026-05-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_bet_betselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.CharField(default='Fútbol', help_text='Deporte de la liga (Fútbol, Baloncesto, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='league',
            name='api_id',
            field=models.IntegerField(help_text='ID oficial de la liga en la API externa', unique=True),
        ),
    ]
