# Generated by Django 5.0.14 on 2026-05-27 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        help_text="Documento Nacional de Identidad peruano de 8 dígitos",
                        max_length=8,
                        unique=True,
                        verbose_name="DNI Peruano",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        help_text="Se requiere tener mínimo 18 años para operar en la plataforma",
                        verbose_name="Fecha de Nacimiento",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pendiente de Verificación"),
                            ("verified", "Verificado"),
                            ("blocked", "Bloqueado por Administrador"),
                            ("self_excluded", "Autoexcluido por el Usuario"),
                        ],
                        default="pending_verification",
                        max_length=30,
                        verbose_name="Estado de Verificación",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
    ]
