# Generated by Django 6.0.4 on 2026-05-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('WALLET_MOVEMENT', 'Movimiento de Billetera'), ('BET_STATUS_CHANGE', 'Cambio de Estado de Apuesta'), ('ODDS_CHANGE', 'Variación de Cuotas')], max_length=50, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(verbose_name='Detalles del Evento (JSON)')),
                ('previous_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash del Registro Anterior')),
                ('current_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hash del Registro Actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['id'],
            },
        ),
    ]
