# Generated by Django 5.0.14 on 2026-05-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogentry",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("WALLET_MOVEMENT", "Movimiento de Billetera"),
                    ("BET_STATUS_CHANGE", "Cambio de Estado de Apuesta"),
                    ("ODDS_CHANGE", "Variación de Cuotas"),
                    ("EVENT_STATUS_CHANGE", "Cambio de Estado de Evento"),
                    ("MARKET_CREATION", "Creación de Mercado"),
                    ("SELECTION_CREATION", "Creación de Selección"),
                ],
                max_length=50,
                verbose_name="Tipo de Evento",
            ),
        ),
    ]
