# -*- coding: utf-8 -*-
# Generated by Django 5.0.x on 2026-05-26 22:44
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('wallet_usuario', 'Billetera del Usuario'), ('casa', 'Caja del Operador'), ('apuestas_pendientes', 'Fondo en Custodia de Apuestas'), ('bonos', 'Fondo de Bonos')], max_length=30, verbose_name='Cuenta Contable')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Monto del movimiento (NUNCA usar float, siempre Decimal)', max_digits=18, verbose_name='Monto')),
                ('direction', models.CharField(choices=[('DEBIT', 'Débito (Salida)'), ('CREDIT', 'Crédito (Entrada)')], help_text='DEBIT = sale dinero, CREDIT = entra dinero', max_length=6, verbose_name='Dirección')),
                ('transaction_id', models.UUIDField(db_index=True, help_text='UUID que agrupa el débito y crédito de una misma operación', verbose_name='ID de Transacción')),
                ('description', models.CharField(blank=True, default='', help_text='Motivo legible del movimiento (ej: Recarga de fichas, Apuesta #123)', max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo inmutable del registro contable', verbose_name='Fecha de Creación')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario asociado (puede ser nulo para movimientos de la casa)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento Contable',
                'verbose_name_plural': 'Movimientos Contables',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['transaction_id'], name='wallet_ledg_transac_e91dba_idx'),
                    models.Index(fields=['user', 'account'], name='wallet_ledg_user_id_b0cd30_idx'),
                ],
            },
        ),
    ]
