# Generated by Django 5.0.14 on 2026-05-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="wallet_ledg_transac_a947a0_idx",
            old_name="wallet_ledg_transac_e91dba_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="wallet_ledg_user_id_84261c_idx",
            old_name="wallet_ledg_user_id_b0cd30_idx",
        ),
    ]
