# Generated by Django 5.0.14 on 2026-05-28 05:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallet",
            "0002_rename_wallet_ledg_transac_e91dba_idx_wallet_ledg_transac_a947a0_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="Monto del Bono"
                    ),
                ),
                (
                    "rollover_multiplier",
                    models.IntegerField(
                        default=6, verbose_name="Multiplicador de Rollover"
                    ),
                ),
                (
                    "required_turnover",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        verbose_name="Monto Total Requerido",
                    ),
                ),
                (
                    "current_turnover",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=18,
                        verbose_name="Rollover Acumulado",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="¿Bono Activo?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Adquisición"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_bonus",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bono de Usuario",
                "verbose_name_plural": "Bonos de Usuarios",
            },
        ),
    ]
