# Generated by Django 6.0.4 on 2026-05-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('MULTIPLE_ACCOUNTS_SAME_IP', 'Múltiples Cuentas desde misma IP'), ('IMMEDIATE_DEPOSIT_CASHOUT', 'Recarga seguida de Cash-out Inmediato'), ('IDENTICAL_BET_PATTERN', 'Patrón de Apuestas Idénticas en Grupo')], max_length=50, verbose_name='Tipo de Actividad')),
                ('description', models.TextField(verbose_name='Descripción de la Alerta')),
                ('payload', models.JSONField(verbose_name='Detalles Forenses (JSON)')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], max_length=10, verbose_name='Severidad de la Alerta')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('REVIEWED', 'Revisada'), ('DISMISSED', 'Desestimada')], default='PENDING', max_length=15, verbose_name='Estado de la Alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Detección')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por Operador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Sospechoso')),
            ],
            options={
                'verbose_name': 'Alerta de Fraude',
                'verbose_name_plural': 'Alertas de Fraude',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserIpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de IP de Usuario',
                'verbose_name_plural': 'Registros de IP de Usuarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
