# Generated by Django 6.0.4 on 2026-05-27 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_until', models.DateTimeField(blank=True, null=True, verbose_name='Excluido Hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_exclusion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Autoexclusión',
                'verbose_name_plural': 'Autoexclusiones',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleGamingLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Límite Diario Activo')),
                ('weekly_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Límite Semanal Activo')),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Límite Mensual Activo')),
                ('pending_daily_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Límite Diario Pendiente')),
                ('pending_weekly_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Límite Semanal Pendiente')),
                ('pending_monthly_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Límite Mensual Pendiente')),
                ('cooldown_until_daily', models.DateTimeField(blank=True, null=True, verbose_name='Cooldown Diario Hasta')),
                ('cooldown_until_weekly', models.DateTimeField(blank=True, null=True, verbose_name='Cooldown Semanal Hasta')),
                ('cooldown_until_monthly', models.DateTimeField(blank=True, null=True, verbose_name='Cooldown Mensual Hasta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_limit', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Límite de Juego Responsable',
                'verbose_name_plural': 'Límites de Juego Responsable',
            },
        ),
    ]
